[package]
name = "diskmap"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]
memmap2.workspace = true

[dev-dependencies]
proptest = { workspace = true }
tempfile = { workspace = true }
