name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Publish opendiskmap
        run: cargo publish -p opendiskmap --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish diskdashmap
        run: cargo publish -p diskdashmap --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
